# -------------------- ISP Module Enable/Disable --------------------
enable:                
  BPC: False
  LCS: False              
  BLC: True
  AAF: False
  AWB: True
  BNR: False           
  CFA: True
  CCM: True
  GTM: True
  GMC: True
  R2Y: True
  CNR: False
  EE:  False
  BCC: True
  HSC: False                
  Y2R: True

# -------------------- Algorithm Params --------------------
RAW_img_path: '.\test_images\IMG_20240123_191409.png' # RAW image path， please change to your own path
RAW_Height: ~
RAW_Width: ~
white_level: 4095
bayer_pattern: RGGB

bad_pixel_threshold: 30

LCS: ~

black_level_r: 256.0
black_level_gr: 256.0
black_level_gb: 256.0
black_level_b: 256.0
alpha: 1.        
beta: 1.                  

AAF: ~

r_gain: 2.45         
b_gain: 3.98      

BNR_method: 'bilateral'

CFA_method: 'opencv'

ccm_matrix:
    - [1.631906, -0.381807, -0.250099]
    - [-0.298296, 1.614734, -0.316438]
    - [0.023770, -0.538501, 1.514732 ]

GTM_method: 'smoothstep'

gamma: 2.0

R2T: ~

CNR_method: 'gaussian'
CNR_threshold: 0.3

edge_enhancement_strength: 0.3

BCC_contrast: 0.1
BCC_brightness: 10

HSC: ~

Y2R: ~
